server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.28.205:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: haetae
    password: 4ZeARKHFMy5GStf3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  banner:
    location: config/banner.txt
  jackson:
    serialization:
      write-dates-as-timestamps: true
logging:
  config: classpath:config/logback.xml
wechat:
  appId: wx551daf14b0dfa9c0
  secret: 77109ce85fbf46043f0eb8d55e23abfa
  SubTemplateId: nwxzBKgDlu7j_zBN1Mq0TTDqux_7-QjFHUhcqZYe_ZA
  AuditTemplateId: i6pErfUiZ1p4iycqGuHTBfbgMd3LtT9_oObbXS_-faI
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    keyid: LTAI4GGRk8m7KQXN7h8bRxGz
    keysecret: bSqAxd53iDVV9Y0Lk3Djt6gnRwAMpC
    bucketname: bucket-chest
    filehost: dev
Yiban:
  appId:
  appSecret:
  redirectUri:
