server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    use-forward-headers: true
  port: 8000
spring:
  datasource:
   # type: com.alibaba.druid.pool.DruidDataSource
   # driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://121.36.28.205:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
   # username: haetae
   # password: 4ZeARKHFMy5GStf3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  banner:
    location: config/banner.txt
  jackson:
    serialization:
      write-dates-as-timestamps: true
logging:
  config: classpath:config/logback.xml

